apiVersion: chatgptcontroller.uucloud.top/v1
kind: ChatGPT
metadata:
  name: example-chatgpt
spec:
  config:
    token: "XXXXXX"
    model: "gpt-3.5-turbo-0301"
    temperature: 0.7
    max_token: 2000
    