apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpt-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpt-cluster-role
subjects:
- kind: ServiceAccount
  name: gpt-manager
  namespace: default