apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpt-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["chatgptcontroller.uucloud.top"]
  resources: ["chatgpts"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]